server:
  port: ${SERVER_PORT:8081}
  max-http-request-header-size: ${MAX_HTTP_HEADER_SIZE:32KB}
spring:
  main:
    allow-circular-references: true
  application:
    name: service-api
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:1GB}
      max-request-size: ${MAX_REQUEST_SIZE:1GB}
  session:
    redis:
      namespace: ${SESSION_NAMESPACE:apitable:session}
      repository-type: indexed
    timeout: ${SESSION_TIMEOUT:30d}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:apitable}?characterEncoding=utf8&autoReconnect=true&useSSL=${MYSQL_SSL_ENABLED:false}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:apitable@com}
  # Redis
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:apitable@com}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}
      timeout: ${REDIS_TIMEOUT:30000}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}
  rabbitmq:
    addresses: amqp://${RABBITMQ_HOST:127.0.0.1}:${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:apitable}
    password: ${RABBITMQ_PASSWORD:apitable@com}
    publisher-returns: true
    publisher-confirm-type: correlated
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 5
        auto-startup: true
        retry:
          enabled: true

    virtual-host: ${RABBITMQ_VHOST:/}
  mail:
    host: ${MAIL_HOST:smtp.apitable.com}
    username: ${MAIL_USERNAME:support@apitable.com}
    password: ${MAIL_PASSWORD:apitable}
    port: ${MAIL_PORT:465}
    protocol: smtp
    properties:
      mail.debug: true
      mail.smtp.auth: true
      mail.smtp.starttls.enable: ${MAIL_STARTTLS_ENABLE:true}
      mail.smtp.starttls.required: ${MAIL_STARTTLS_REQUIRED:true}
      mail.smtp.ssl.enable: ${MAIL_SSL_ENABLE:true}
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  logger:
    max-history-days: ${LOGGER_MAX_HISTORY_DAYS:7}

cookie:
  domain-name: ${DOMAIN_NAME:}
  http-only: ${COOKIES_HTTP_ONLY:true}
  secure: ${COOKIES_SECURE:false}
  same-site: ${COOKIES_SAME_SITE:}
const:
  language-tag: ${DEFAULT_LOCALE:en-US}
  server-domain: ${SERVER_DOMAIN:}
  callback-domain: ${CALLBACK_DOMAIN:}
  oss-image-audit-creatable: ${OSS_IMAGE_AUDIT_CREATABLE:false}
  ossBuckets:
    assets:
      resource-url: ${ASSETS_URL:}
      bucket-name: ${ASSETS_BUCKET:}
      type: ${ASSETS_TYPE:QNY1}
  template-space: ${TEMPLATE_SPACE:spcNTxlv8Drra}
  quote-template-id: ${QUOTE_TEMPLATE_ID:tpll8mltwrZMT}
  quoteEn-template-id: ${QUOTE_EN_TEMPLATE_ID:spcNA5eN3Sj6Q}
  register-quote-templates: ${REGISTER_QUOTE_TEMPLATES:tplZYaYZqaPLE,tplED3FVnX8U6}
  ding-talk-order-datasheet: ${DING_TALK_ORDER_DATASHEET:dstbPAnKDwnPpliqg4}
  cooling-off-period: ${COOLING_OFF_PERIOD:30}
  close-paused-user-cron: ${CLOSE_PAUSED_USER_CRON:0 0 0 * * ?}
limit:
  space-max-count: ${SPACE_MAX_COUNT:10}
  max-file-size: ${EXPORT_MAX_FILE_SIZE:20971520}
  max-column-count: ${MAX_COLUMN_COUNT:200}
  max-row-count: ${MAX_ROW_COUNT:50000}
  template-max-count: ${TEMPLATE_MAX_COUNT:20}
  dsb-widget-max-count: ${DSB_WIDGET_MAX_COUNT:30}
  dst-robot-max-count: ${DST_ROBOT_MAX_COUNT:10}
socket:
  domain: ${SOCKET_DOMAIN:http://127.0.0.1:3333/socket}

email:
  personal: ${EMAIL_PERSONAL:APITable}
  from: ${MAIL_FROM:}

cte-sql:
  enabled: ${CTE_SQL_ENABLED:true}

starter:
  socketio:
    client:
      url: ${SOCKET_URL:http://127.0.0.1:3002}
      path: ${SOCKET_PATH:/notification}
      reconnection-attempts: ${SOCKET_RECONNECTION_ATTEMPTS:2}
      reconnection-delay: ${SOCKET_RECONNECTION_DELAY:1000}
      timeout: ${SOCKET_TIMEOUT:1000}
  oss:
    enabled: ${OSS_ENABLED:true}
    type: ${OSS_CLIENT_TYPE:aws}
    aws:
      access-key-id: ${AWS_ACCESS_KEY:}
      access-key-secret: ${AWS_ACCESS_SECRET:}
      endpoint: ${AWS_ENDPOINT:s3-cn-south-1.qiniucs.com}
      region: ${AWS_REGION:cn-south-1}
    qiniu:
      access-key: ${QINIU_ACCESS_KEY:' '}
      secret-key: ${QINIU_SECRET_KEY:' '}
      region: ${QINIU_REGION:z2}
      download-domain: ${QINIU_DOWNLOAD_DOMAIN:aitable.ai}
      upload-url: ${QINIU_UPLOAD_URL:https://up-z2.qiniup.com}
      callback:
        enabled: ${QINIU_CALLBACK_ENABLED:false}
        url: ${QINIU_CALLBACK_URL:http://fktcca.natappfree.cc/api/v1/asset/qiniu/uploadCallback}
        body-type: ${QINIU_CALLBACK_BODY_TYPE:application/json}
    huawei-cloud:
      access-key: ${HUAWEICLOUD_OBS_ACCESS_KEY:}
      secret-key: ${HUAWEICLOUD_OBS_SECRET_KEY:}
      endpoint: ${HUAWEICLOUD_OBS_ENDPOINT:obs.cn-south-1.myhuaweicloud.com}
    minio:
      endpoint: ${MINIO_ENDPOINT:http://minio:9000}
      access-key: ${MINIO_ACCESS_KEY:apitable}
      secret-key: ${MINIO_SECRET_KEY:apitable@com}
      bucket-policy: ${MINIO_BUCKET_POLICY:'{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:GetBucketLocation"],"Resource":["arn:aws:s3:::vk-assets-ltd"]},{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:ListBucket"],"Resource":["arn:aws:s3:::vk-assets-ltd"],"Condition":{"StringEquals":{"s3:prefix":["*.*"]}}},{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:GetObject"],"Resource":["arn:aws:s3:::vk-assets-ltd/*.**"]}]}'}
    signature:
      enabled: ${OSS_SIGNATURE_ENABLED:false}
      model: ${OSS_SIGNATURE_MODE:CDN_TIMESTAMP_ANTI_LEECH}
      expire-second: ${OSS_SIGNATURE_EXPIRE_SECOND:7200}
      encrypt-key: ${OSS_SIGNATURE_CDN_ENCRYPT_KEY:}
  sms:
    enabled: ${SMS_ENABLED:false}
    local-area-code: ${SMS_LOCAL_AREA_CODE:+86}
    local:
      type: ${SMS_LOCAL_TYPE:tencent}
      tencent:
        app-id: ${SMS_TENCENT_APP_ID:}
        app-key: ${SMS_TENCENT_APP_KEY:}
        sign: ${SMS_TENCENT_SIGN:Cloud}
    outland:
      type: ${SMS_OUTLAND_TYPE:yunpian}
      yunpian:
        apikey: ${SMS_YUNPIAN_APIKEY:}
  mail:
    enabled: ${MAIL_ENABLED:false}
    type: ${MAIL_TYPE:smtp}
    region: ${MAIL_REGION:}
    from: ${MAIL_FROM:}
    reply: ${MAIL_REPLY:}
    tencent:
      secret-id: ${MAIL_TENCENT_SECRET_ID:}
      secret-key: ${MAIL_TENCENT_SECRET_KEY:}


sentry:
  dsn: ${SENTRY_DSN:}
  send-default-pii: true
  environment: ${ENV}
  use-git-commit-id-as-release: false
  max-breadcrumbs: 150
  enable-tracing: true
  traces-sample-rate: 1.0
  logging:
    minimum-breadcrumb-level: debug
    minimum-event-level: info

grpc:
  server:
    port: ${BACKEND_GRPC_PORT:8083}
  client:
    nest-grpc-server:
      address: ${NEST_GRPC_ADDRESS:static://localhost:3334}
    dingtalk-grpc-server:
      address: ${DINGTALK_GRPC_ADDRESS:}
      security:
        clientAuthEnabled: false
        authorityOverride: ${DINGTALK_GRPC_AUTHORITY:}

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${API_DOCS_ENABLED:false}

system:
  default-time-zone: ${DEFAULT_TIME_ZONE:UTC}
  test-enabled: ${TEST_ENABLED:false}

databus:
  client:
    host: ${DATABUS_SERVER_BASE_URL:http://127.0.0.1:8625}
