name: build

on:
  push:
    branches:
      - "develop"
      - "release/**"
    tags:
      - "v*"
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build-test: ## build only local for test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "corretto"
          cache: "gradle"
      - name: Test
        run: |
          make install
          make build

  unit-test: ## unit test with docker-compose.unit-test.yaml
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: [ test-ut-backend-docker, test-ut-room-docker, _test-ut-core ]
    steps:
      - uses: actions/checkout@v3
      - name: Running Test
        shell: bash
        run: |
          make ${{ matrix.command }}

  build-push: ## build and push to docker registry
    needs: unit-test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    env:
      APITABLE_DOCKER_HUB_TOKEN: ${{ secrets.APITABLE_DOCKER_HUB_TOKEN }}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      # - uses: satackey/action-docker-layer-caching@v0.0.11
      #   continue-on-error: true
      - name: Build APITable and Push
        run: |
          make buildpush-docker
